#!/usr/bin/env bash
pip3 install --upgrade pip
pip3 install -e . --upgrade --no-cache-dir --progress-bar off

cd external/gym-tictactoe
echo "installing gym-tictactoe 2d"
pip3 install -e . --upgrade --no-cache-dir --progress-bar off
cd ../..

