num_episodes: 1000
num_iterations: 1000
out_image: ucb_egreedy_nonstationary001variance
env_name: BanditTenArmedGaussian-v0
arms: 10

nonstationary: {
  mu: 0,
  sigma: 0.01
}

agents: [
{
  policy: "UpperConfidenceBound",
  learning: "WeightedAveraging",
  kwargs: {
    confidence: 2,
    learning_rate: 0.1,
  }
},
{
  policy: "EGreedy",
  learning: "WeightedAveraging",
  kwargs: {
    exploratory_rate: 0.1,
    learning_rate: 0.1,
  }
},
]